modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="signbuilder"
version="1.0.7"
displayName="SignBuilder"
authors="BoranMandaci & destan"
description='''Mode for creating 3D letters, numbers and symbols'''

[[dependencies.signbuilder]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.signbuilder]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
